name: analyze test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: yarn install --immutable
      - name: lint check
        run: yarn lint
      - name: format check
        run: yarn format
